# Signup Activation Rate

New TikTok users sign up with their emails. They confirmed their signup by replying to the text confirmation to activate their accounts. Users may receive multiple text messages for accounting confirmation until they have confirmed their new account.

A senior analyst is interested to know the activation rate of specified users in the `emails` table. Write a query to find the activation rate. Round the percentage to 2 decimal places.

Definitions:

* `emails` table contain the information of user signup details.
* `texts` table contains the users' activation information.

Assumptions:

* The analyst is interested in the activation rate of specific users in the `emails` table, which may not include all users that could potentially be found in the `texts` table.
* For example, user 123 in the `emails` table may not be in the `texts` table & vice versa.

"Confirmed" in `signup_action` means the user has activated their account & successfully completed the signup process.

# Answer

This is the `emails2` table:

```
CREATE TABLE emails2 (
	email_id smallint,
	user_id smallint,
	signup_date timestamp
);

INSERT INTO emails2
VALUES (125, 7771, '2022-06-14 00:00:00'),
	   (236, 6950, '2022-07-01 00:00:00'),
	   (433, 1052, '2022-07-09 00:00:00'),
	   (450, 8963, '2022-08-02 00:00:00'),
	   (555, 6633, '2022-08-09 00:00:00'),
	   (499, 2500, '2022-08-08 00:00:00');

SELECT * FROM emails2;
```

<img src = "emails2 Table.png" width = "600" style = "margin:auto"/>

This is the `texts2` table:

```
CREATE TABLE texts2 (
	text_id smallint,
	email_id smallint,
	signup_action text
);

INSERT INTO texts2
VALUES (6878, 125, 'Confirmed'),
	   (6994, 236, 'Confirmed'),
	   (8950, 450, 'Not Confirmed'),
	   (6920, 236, 'Not Confirmed'),
	   (8966, 450, 'Not Confirmed'),
	   (8010, 499, 'Not Confirmed');

SELECT * FROM texts2;
```

<img src = "texts2 Table.png" width = "600" style = "margin:auto"/>

Based on the assumptions, I might have to perform a full outer join.

```
SELECT round((count(*) FILTER (WHERE signup_action = 
	   	   'Confirmed'))::numeric / count(*), 2)
		   AS confirm_rate
FROM emails2
FULL OUTER JOIN texts2
	ON emails2.email_id = texts2.email_id
WHERE signup_action IS NOT NULL;
```

<img src = "Signup Confirmation Rate.png" width = "600" style = "margin:auto"/>

The confirmation rate is 33%. Users without `signup_action` values were not part of the calculation.